services:
  smtp-relay:
    image: ghcr.io/fiordhraoi/postfix-smtp-relay:latest
    network_mode: host
    env_file:
      - path: .env
        format: raw
    restart: unless-stopped
    stop_grace_period: 60s
    cap_drop: [ALL]
    cap_add: [CHOWN, DAC_OVERRIDE, FOWNER, FSETID, SETGID, SETUID, NET_BIND_SERVICE, KILL]
    security_opt:
      - no-new-privileges:true
    volumes:
      - queue:/var/spool/postfix
      - tls:/var/lib/postfix-tls
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
volumes:
  queue:
  tls:
